services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - type: bind
        source: ./app
        target: /app
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
